services:
  gitlab_server:
    build: GitLab/.
    container_name: GitLabCE
    image: gitlab-ce-ubuntu
    tty: true
    restart: always
    # hostname: 'gitlab.example.com'
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
    #     # Add any other gitlab.rb configuration here, each on its own line
    #     external_url 'https://gitlab.example.com:8001' '8001:80'
    #     gitlab_rails['gitlab_shell_ssh_port'] = 2424
    # ports:
    #   - '80:80'
    #   - '4431:443'
    #   - '2424:22'
    volumes:
      - './storage/gitlab/config:/etc/gitlab'
      - './storage/gitlab/logs:/var/log/gitlab'
      - './storage/gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      cicd-networks:
        ipv4_address: 172.0.10.3

networks:
  cicd-networks:
    ipam:
      config:
        - subnet: 172.0.10.0/24

