services:
  gitlab_server:
    build: 
      context: ./GitLab
      dockerfile: Dockerfile
    container_name: GitLabCE
    image: gitlab-ce-ubuntu
    tty: true
    restart: always
    # hostname: 'gitlab.example.com'
    # environment:
    #   GITLAB_OMNIBUS_CONFIG: |
    #     # Add any other gitlab.rb configuration here, each on its own line
    #     external_url 'https://gitlab.example.com:8001' '8001:80'
    #     gitlab_rails['gitlab_shell_ssh_port'] = 2424
    # ports:
    #   - '80:80'
    #   - '4431:443'
    #   - '2424:22'
    volumes:
      - './storage/gitlab/config:/etc/gitlab'
      - './storage/gitlab/logs:/var/log/gitlab'
      - './storage/gitlab/data:/var/opt/gitlab'
      - './storage/gitlab/config-before-start:/gitlab-config/before'
      - './storage/gitlab/config-before-start-done:/gitlab-config/before-done'
      - './storage/gitlab/config-after-start:/gitlab-config/after'
      - './storage/gitlab/config-after-start-done:/gitlab-config/after-done'
    shm_size: '256m'
    networks:
      cicd-networks:
        ipv4_address: 172.0.10.3
  mailhog:
    image: mailhog/mailhog
    container_name: Mailhog
    restart: always
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    networks:
      cicd-networks:
        ipv4_address: 172.0.10.4

networks:
  cicd-networks:
    ipam:
      config:
        - subnet: 172.0.10.0/24

